pkg/check/node_provider.go
Fix a copy-paste error in a check name.
@openshift/storage
=> Bug 1908344: Fix CheckNodeProviderID name

README.md
=> Remove WIP note

pkg/check/interface.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1929824
=> Bug 1929824: Disable PV check

pkg/operator/operator.go, pkg/operator/pool.go, pkg/operator/pool_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1939555
=> Fixes 1939555: Fix deadlock when enqueing functions into the pool

pkg/operator/operator.go, pkg/operator/pool.go, pkg/operator/pool_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1936975
=> [4.7] Bug 1936975: Fix deadlock when enqueing functions into the pool

pkg/operator/operator.go
Make sure that the error message in Available condition is set on every sync() call, not only when the checks actually run.
Without this PR, the condition is sent only on `sync()` that actually runs the checks and it gets cleared by other subsequent `sync()` calls.
cc @gnufied
=> Bug 1943719: Save error in Available message on every sync

pkg/check/datastore.go, pkg/check/datastore_test.go
NFS datastore type may be deprecated upstream and we want to know how many clusters use them.
(see https://vsphere-csi-driver.sigs.k8s.io/compatiblity_matrix.html)
The metric is collected in `CheckStorageClasses()`, therefore the default data store must be checked there if a StorageClass does not refer to a specific one. Extra care is made to collect each DS only once.
The simulated vCenter used for unit tests has all datastores with type `OTHER`. I did not change that to make sure the files can be re-generated later without manual changes.
Example:
```
vsphere_datastore_total{type="vsan"} 2
```
=> Bug 1904507: Add metrics for Datastore types

pkg/check/framework_test.go, pkg/check/info.go, pkg/check/info_test.go, pkg/check/node_esxi_version.go, pkg/check/node_esxi_version_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2000294
=> Bug 2000294: Report esxi api versions

pkg/check/folder.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2003857
=> Fix check for datastore.browse

pkg/check/datastore.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2005811
=> Bug 2005811: Ignore datastore list checks

pkg/operator/vsphere_check.go
Resolves a slow vSphere session leak: https://bugzilla.redhat.com/show_bug.cgi?id=2011903
=> Bug 2011903: Deferred logout after checks are run

pkg/check/count_pv_types.go, pkg/check/count_pv_types_test.go, pkg/check/interface.go
=> Add new metric for counting rwx volumes

pkg/operator/operator.go
=> we are already blocking upgrades in vsphere-csi-driver-operator

pkg/check/node_perf.go
TL;DR
The purpose of this PR is to change the alert criteria to take an average of the disk latency over the aggregate of the metric history set which stores up to approximately the last hour of metrics.  
The Problem
CI has uncovered a scenario where intermittent disk latency of over 100ms results in the `NodePerfCheck` test failing even though disk latency is not persistently poor for the node in question.  The intention of this change is to only fire the alert if there is persistent latency over 100ms.
Why is the alert being averaged over the period of an hour? 
The thought behind this is that if no problems are detected by the vSphere problem detector the check is only run, at most, every hour.  While high instantaneous latency events may be missed by averaging, a persistently poor …
=> Bug 2055729: change NodePerfCheck criteria to be based on average latency

pkg/check/framework_test.go, pkg/check/interface.go, pkg/check/node_esxi_version.go, pkg/check/node_esxi_version_test.go, pkg/check/node_hw_version.go, pkg/check/node_hw_version_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2042446
=> Bug 2042446: Fix stale metrics by explicitly zeroed out old metrics

pkg/check/datastore.go, pkg/check/framework_test.go, pkg/check/info.go, pkg/check/interface.go, pkg/check/node_esxi_version.go, pkg/check/node_esxi_version_test.go, pkg/check/node_hw_version.go, pkg/check/node_hw_version_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2059255
=> Bug 2059255: Fix stale metrics by resetting them

pkg/check/count_pv_types.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2058217
=> Bug 2058217: fix docs for rwx volumes

pkg/check/datastore.go, pkg/check/framework_test.go, pkg/check/info.go, pkg/check/interface.go, pkg/check/node_esxi_version.go, pkg/check/node_esxi_version_test.go, pkg/check/node_hw_version.go, pkg/check/node_hw_version_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2060214
=> Bug 2060214:Fix stale metrics

pkg/check/count_pv_types.go, pkg/check/count_pv_types_test.go, pkg/check/interface.go
Emit metrics for counting zonal PVs
=> OCPBUGS-5508: Add a count of zonal volumes

pkg/check/framework_test.go, pkg/check/interface.go, pkg/check/util.go, pkg/check/zones.go, pkg/check/zones_test.go, pkg/operator/vsphere_check.go, vendor/github.com/vmware/govmomi/vapi/library/library.go, vendor/github.com/vmware/govmomi/vapi/library/library_file.go, vendor/github.com/vmware/govmomi/vapi/library/library_item.go, vendor/github.com/vmware/govmomi/vapi/library/library_item_downloadsession_file.go, vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession.go, vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession_file.go, vendor/github.com/vmware/govmomi/vapi/simulator/simulator.go, vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_ovf.go, vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_vmtx.go, vendor/modules.txt
Added logic for VPD to check tags related to multi-zone support so that cluster admin can be notified of configuration issues via alerts.
=> OCPBUGS-10988: day 2 multi-zone configuration fails if tags are not defined

pkg/check/node_perf.go, pkg/check/node_perf_test.go
Added block check for unknown role types.
=> OCPBUGS-7353: CheckNodePerf firing on infra nodes

pkg/check/info.go
Fixes https://issues.redhat.com/browse/OCPBUGS-14023
=> OCPBUGS-14023: Log vcenter version information

.snyk, OWNERS, OWNERS_ALIASES
- [STOR-1688](https://issues.redhat.com//browse/STOR-1688): Chore: add .snyk file to ignore false positives
- Chore: Update OWNERS_ALIASES
=> STOR-1688: Chore: add .snyk file to ignore false positives

pkg/operator/vsphere_check.go
Fixes https://issues.redhat.com/browse/OCPBUGS-25372
=> OCPBUGS-25372: Fix VPD crash when vm is not found

pkg/operator/vsphere_check.go
=> OCPBUGS-22994: Check if username contains a fully qualified domain name

pkg/cache/cache.go
[SPLAT-1209](https://issues.redhat.com//browse/SPLAT-1209)
- Updated cache to added known datacenters to error text when datacenter is not found
=> SPLAT-1209: Enhance datacenter not found to contain list of known datacenters

pkg/operator/operator.go
Fixes https://issues.redhat.com/browse/OCPBUGS-39358
=> OCPBUGS-39358: Fix VSphereProblemDetector waiting 24 hours after changing  managementState from "Removed" to "Managed"

go.mod, go.sum, pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/operator/operatorclient.go, pkg/operator/starter.go, vendor/github.com/imdario/mergo/.gitignore, vendor/github.com/imdario/mergo/.travis.yml, vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md, vendor/github.com/imdario/mergo/LICENSE, vendor/github.com/imdario/mergo/README.md, vendor/github.com/imdario/mergo/doc.go, vendor/github.com/imdario/mergo/map.go, vendor/github.com/imdario/mergo/merge.go, vendor/github.com/imdario/mergo/mergo.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/test_operator_client.go, vendor/modules.txt
Alternative to: https://github.com/openshift/vsphere-problem-detector/pull/180
=> OCPBUGS-53217: replace operator client
