- go.mod
- pkg/check/dummy.go
- pkg/check/info.go
- pkg/check/interface.go
- pkg/operator/metrics.go
- pkg/operator/operator.go
- pkg/operator/vmware.go
- vendor/modules.txt
Refactor the checks to have separate cluster-level ones and node-level ones - we want to track metrics for each node separately to be able to identify faulty nodes easily. In addition, several node checks will need VM object from vSphere, so let's load it only once.
For each cluster-level check, report duration (incl. total number of runs) + number of failed runs.
```
vsphere_cluster_check_duration_seconds_bucket{check="Dummy",le="0.1"} 4
vsphere_cluster_check_duration_seconds_bucket{check="Dummy",le="0.25"} 4
vsphere_cluster_check_duration_seconds_bucket{check="Dummy",le="0.5"} 4
vsphere_cluster_check_duration_seconds_bucket{check="Dummy",le="1"} 4
vsphere_cluster_check_duration_seconds_bucket{check="Dummy",le="2.5"} 4
vsphere_cluster_check_duration_seconds_bucket{check="Dummy",le="5"} 4 …
```
> Add metrics of executed checks

- pkg/operator/metrics.go
- pkg/operator/operator.go
Report only these counters:
```
vsphere_cluster_check_total
vsphere_cluster_check_errors
vsphere_node_check_total
vsphere_node_check_errors
```
Full histogram per check per node could be too heavy for Prometheus database.
> Remove histogram from metrics

- pkg/operator/operator.go
- pkg/operator/vmware.go
The operator should set Available: true and not to do anything when running on a non-vsphere cloud.
Reworked detection of the first `sync()` call a bit, it should be more obvious now.
> Don't set Degraded when on other clouds

- pkg/check/interface.go
- pkg/check/node_esxi_version.go
- pkg/check/node_hw_version.go
- pkg/check/node_provider.go
- pkg/check/node_uuid.go
- pkg/operator/operator.go
```
vsphere_esxi_version_total{version="7.0.0"} 3
vsphere_node_hw_version_total{hw_version="vmx-13"} 6
```
* Using HW version as reported by vSphere, i.e. "vmx-N".
* Reworked node check interface:  `NodeCheck` is now an interface that can collect some information / cache  during check of each node to be able to report cumulative metrics of nodes.
* As advantage, all node metrics will be separate functions, for easier readability.
* Will be reused to collect other node-specific metrics, like ESXi host versions.
@openshift/storage
> Add metrics with node HW version and ESXi host version

- go.mod
- pkg/check/interface.go
- pkg/check/node_esxi_version.go
- pkg/check/node_hw_version.go
- pkg/operator/operator.go
- pkg/operator/pool.go
- vendor/golang.org/x/sync/semaphore/semaphore.go
- vendor/modules.txt
The operator should run all checks in parallel. At the same time, the number of goroutines should be limited, not to spam vSphere / Kubernetes API too much.
* Introducing `CheckThreadPool`, that spawns a goroutine for each check, however, makes sure that only few of them can run in parallel. The rest of them wait for a semaphore.
* Since everything runs in parallel, introducing `ResultCollector` that collects results of each check. When a check is run multiple times (e.g. separately for each node), it collects all its errors.
WIP:
* unit tests (as separate PR)
* ~update the node checks to run in parallel - they will need a lock when accessing their caches.~
> Bug 1904502: Parallelize all checks

- pkg/operator/metrics.go
Prometheus doc says that counter metric should end with "_total".
> Bug 1915818: Add "total" suffix to counter metrics

- .gitignore
- pkg/operator/metrics.go
- pkg/operator/operator.go
It is very tricky to report alerts on metrics that are emitted sporadically or at very long interval. Using gauge for this type simplifies alerting logic.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1916379
> Bug 1916379: Change metric for errors to gauge

- pkg/check/interface.go
- pkg/check/node_esxi_version.go
- pkg/check/node_hw_version.go
- pkg/check/node_provider.go
- pkg/check/node_uuid.go
- pkg/operator/operator.go
Call FinishCheck on all node checks when checks are complete. This allows various checks to report their metrics.
@openshift/storage
> Bug 1915859: Fix reporting of node metrics

- pkg/check/datastore.go
Use the same logic as Kubernetes to truncate cluster-id in volume names. This will fix false alerts when the cluster ID is too long.
> Bug 1926943: Fix volume name length check

- pkg/check/datastore.go
- pkg/check/datastore_test.go
- pkg/check/framework_test.go
- pkg/check/interface.go
- pkg/check/node_esxi_version_test.go
- pkg/check/node_hw_version_test.go
- pkg/check/node_provider_test.go
- pkg/check/node_uuid_test.go
- pkg/operator/kubeclient.go
- pkg/operator/metrics.go
- pkg/operator/operator.go
- pkg/operator/starter.go
Clusters that do not have correct credentials to vCenter should not get degraded when vsphere-problem-detector cannot connect to it.
Instead, keep the cluster `Availabe=true` and only report a new metric + alert on it (in a separate PR)
Add the error message to `Availabe=true` condition, so it can be found without digging through logs:
```
type: VSphereProblemDetectorControllerAvailable
status: "True"
reason: SyncFailed
message: 'failed to connect to vcenter.sddc-44-236-21-251.vmwarevmc.com: ServerFaultCode:
Cannot complete login due to an incorrect user name or password.'
```
cc @openshift/storage
> Bug 1943719: Don't degrade cluster on connection error

- pkg/operator/metrics.go
- pkg/operator/operator.go
- pkg/operator/vmware.go
Adding a check for a new line in credentials when unable to connect to vCenter.
- Encode a credentials with `echo` and excluded `-n`.  For example:
~~~
echo mypassword | base64 -w0
~~~
- Update configmap `vsphere-creds` in `kube-system`
- Monitor vsphere-problem-detector logs
~~~
E0514 13:32:25.504764       1 operator.go:138] Failed to run checks: failed to connect to vcenter.domain.com: password in credentials contains new line
I0514 13:32:25.505070       1 operator.go:152] Scheduled the next check in 1m0.377112854s (2021-05-14 13:33:22.454966225 +0000 UTC m=+62.914630440)
~~~
> Check for a new line in credentials when unable to connect to vCenter

- pkg/check/interface.go
- pkg/check/node_perf.go
The objective of this PR is to monitor disk latency for master nodes.  This enhancement also provides the ability to monitor other metrics for master, workers, or both depending on the definition.
> Adding node performance check based on vCenter performance metrics

- pkg/operator/operator.go
4.9 vSphere CI revealed a SyncErrors.  While reviewing the code that generates the sync error, a regression was found that was introduced in https://github.com/openshift/vsphere-problem-detector/pull/41.  The intent of this PR is resolve that regression by clearing the SyncError metric when there is no SyncError.
> Clear SyncError if there is no sync failure

- pkg/operator/operator.go
- pkg/operator/operator_test.go
because metrics are persisted and conditons are not updated when
checks aren't performed. This will simplify internal logic of the operator.
> We don't actually need to store last check result in operator

- .ci-operator.yaml
- Dockerfile
- pkg/dependencymagnet/dependencymagnet.go
Reconciling with https://github.com/openshift/ocp-build-data/tree/5b89f5b601508a0bcc0399fd3f34b7aa2e86e90e/images/vsphere-problem-detector.yml
Replaces https://github.com/openshift/vsphere-problem-detector/pull/62
/cc @openshift/storage
> Updating vsphere-problem-detector images to be consistent with ART

- pkg/operator/operator.go
- pkg/operator/vmware.go
Backport of https://github.com/openshift/vsphere-problem-detector/pull/60 to 4.9.z
> Bug 2033733: Deferred logout after checks are run

- pkg/check/count_pv_types.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2051881
Working metric:
```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"vsphere_rwx_volumes_total","container":"vsphere-problem-detector-operator","endpoint":"vsphere-metrics","job":"vsphere-problem-detector-metrics","namespace":"openshift-c
luster-storage-operator","pod":"vsphere-problem-detector-operator-5b6c67f8df-76ncr","service":"vsphere-problem-detector-metrics"},"value":[1644347281.224,"2"]}]}}
```
> Bug 2051881: Dont forget to register metrics before emitting

- pkg/check/count_pv_types.go
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=2052609
> Bug 2052609: Dont forget to register metrics before emitting

- pkg/check/datastore.go
- pkg/check/datastore_test.go
- pkg/check/interface.go
With CSI it will become less relevant and only solution is basically renaming the datastore(which breaks existing PV).
As for systemd, it just means that systemd is not managing those mount point as units. But I don't think it is necessary in this case because kubelet is already doing it.
Fixes https://issues.redhat.com/browse/OCPBUGSM-44982
> Bug 2092811:Lets remove datastore length checks for now

- pkg/check/info.go
- pkg/check/info_test.go
This commit adds a single metric - vcenter build
number. This will help us determine the exact
vcenter release a customer is using.
> OCPBUGS-10794: Add build number to metrics

- pkg/check/zones.go
- pkg/check/zones_test.go
This PR resolves an issue when `vsphere`
```
platformSpec:
type: VSphere
vsphere: {}
```
is unset.
- Adds a check for `inf.Spec.PlatformSpec.VSphere`, logs and returns if nil.
- Adds a additional unit test to check this condition.
> OCPBUGS-14029: In UPI clusters VSphere platform could be nil

- pkg/check/cache.go
- pkg/check/cache_test.go
- pkg/check/datastore.go
- pkg/check/framework_test.go
- pkg/check/interface.go
- pkg/check/util.go
- pkg/operator/vsphere_check.go
The cache is fresh for each check run. It caches all datacenters that any check loaded + all their datastores, even though not all of them may be used by the checks.
I still need to figure our how to unit-test this.
@openshift/storage
> OCPBUGS-14177: Add a cache datacenters and datastores

- pkg/operator/vsphere_check.go
Fixes https://issues.redhat.com/browse/OCPBUGS-14829
We could emit a metric here as well, and create alerts but I am worried about customers then complaining about noisy alerts.
> OCPBUGS-14829: Warn usernames without domain name

- pkg/check/framework_test.go
- pkg/check/interface.go
- pkg/check/node_cbt.go
- pkg/check/node_cbt_test.go
- pkg/check/node_esxi_version.go
- pkg/check/node_esxi_version_test.go
- pkg/check/node_hw_version.go
- pkg/check/node_hw_version_test.go
- pkg/metrics/collector.go
- pkg/metrics/collector_test.go
- pkg/operator/operator.go
- pkg/operator/vsphere_check.go
This change frees up individual check from storing the metrics that can change and need not be emitted anymore.
Fixes OCPBUGS-7413
> OCPBUGS-7413: Use collector for ephemeral metrics

- pkg/check/datastore.go
- pkg/check/datastore_test.go
Log a warning instead.
CC @openshift/storage
> OCPBUGS-34563: Drop event when CheckDefaultDatastore fails

- pkg/cache/cache.go
- pkg/check/datastore.go
- pkg/check/permissions.go
- pkg/check/util.go
- pkg/check/zones.go
- pkg/log/log.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/operator/vsphere_check.go
vsphere-problem-detector must not emit any events if State is Removed in ClusterCSIDriver. Also, it must use `klog.Infof()` instead of `klog.Errorf()` in this case.
> STOR-1767: Silence vsphere-problem-detector if State is Removed

- pkg/cache/cache.go
- pkg/check/datastore.go
Improve log messages so that they're not perceived as errors by users and engineers:
- do not log misleading messages (saying we check permissions when we do other stuff and log it)
- if there's datacenter that can not be reached and is not related to OCP it is expected and log messages should make that clear
> OCPBUGS-52964: improve datastore check messages
